algorithm:
  type: GA  # GA|SA|ACO|TS|DP|RL
  parameters:
    GA:
      populationSize: 100
      maxGenerations: 1000
      mutationRate: 0.1
    SA:
      initialTemp: 100.0
      coolingRate: 0.95
      finalTemp: 0.01
    ACO:
      antCount: 50
      pheromoneWeight: 1.0
      evaporationRate: 0.1
    TS:
      tabuListSize: 20
      maxIterations: 500
    DP:
      maxStates: 1000000
    RL:
      episodes: 1000
      learningRate: 0.1
      discountFactor: 0.9
      epsilon: 0.1

dataGeneration:
  strategy: "B"          # 生成策略：A-纯随机，B-保底可行
  timeConstraint: 120.0  # 总时间约束
  minTimePerCustomer: 2.0
  maxTimePerCustomer: 10.0
  minDistance: 1.0
  maxDistance: 10.0
  costFactor:
    min: 0.8
    max: 1.2